
package com.gs.ce.ws.core.services.client.token;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "token1Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Token1Soap {


    /**
     * 
     * @param vIdent
     * @param param1
     * @param param2
     * @return
     *     returns com.gs.ce.ws.core.services.client.token.ArrayOfString
     */
    @WebMethod(action = "http://tempuri.org/getToken")
    @WebResult(name = "getTokenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getToken", targetNamespace = "http://tempuri.org/", className = "com.gs.ce.ws.core.services.client.token.GetToken")
    @ResponseWrapper(localName = "getTokenResponse", targetNamespace = "http://tempuri.org/", className = "com.gs.ce.ws.core.services.client.token.GetTokenResponse")
    public ArrayOfString getToken(
        @WebParam(name = "Param1", targetNamespace = "http://tempuri.org/")
        String param1,
        @WebParam(name = "Param2", targetNamespace = "http://tempuri.org/")
        String param2,
        @WebParam(name = "v_ident", targetNamespace = "http://tempuri.org/")
        String vIdent);

}
