
package com.gs.ce.ws.core.services.client.token;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "token_esp", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/C:/ServiciosLogin5/wsdl/portal.socio.gs/Login5/token_esp/token_esp.asmx.wsdl")
public class TokenEsp
    extends Service
{

    private final static URL TOKENESP_WSDL_LOCATION;
    private final static WebServiceException TOKENESP_EXCEPTION;
    private final static QName TOKENESP_QNAME = new QName("http://tempuri.org/", "token_esp");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/ServiciosLogin5/wsdl/portal.socio.gs/Login5/token_esp/token_esp.asmx.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TOKENESP_WSDL_LOCATION = url;
        TOKENESP_EXCEPTION = e;
    }

    public TokenEsp() {
        super(__getWsdlLocation(), TOKENESP_QNAME);
    }

    public TokenEsp(WebServiceFeature... features) {
        super(__getWsdlLocation(), TOKENESP_QNAME, features);
    }

    public TokenEsp(URL wsdlLocation) {
        super(wsdlLocation, TOKENESP_QNAME);
    }

    public TokenEsp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TOKENESP_QNAME, features);
    }

    public TokenEsp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TokenEsp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TokenEspSoap
     */
    @WebEndpoint(name = "token_espSoap")
    public TokenEspSoap getTokenEspSoap() {
        return super.getPort(new QName("http://tempuri.org/", "token_espSoap"), TokenEspSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TokenEspSoap
     */
    @WebEndpoint(name = "token_espSoap")
    public TokenEspSoap getTokenEspSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "token_espSoap"), TokenEspSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TOKENESP_EXCEPTION!= null) {
            throw TOKENESP_EXCEPTION;
        }
        return TOKENESP_WSDL_LOCATION;
    }

}
