
package com.gs.ce.ws.core.services.client.token;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "token_espSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TokenEspSoap {


    /**
     * 
     * @param wcadenaoriginal
     * @return
     *     returns com.gs.ce.ws.core.services.client.token.ArrayOfString
     */
    @WebMethod(action = "http://tempuri.org/recibepeticion")
    @WebResult(name = "recibepeticionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "recibepeticion", targetNamespace = "http://tempuri.org/", className = "com.gs.ce.ws.core.services.client.token.Recibepeticion")
    @ResponseWrapper(localName = "recibepeticionResponse", targetNamespace = "http://tempuri.org/", className = "com.gs.ce.ws.core.services.client.token.RecibepeticionResponse")
    public ArrayOfString recibepeticion(
        @WebParam(name = "wcadenaoriginal", targetNamespace = "http://tempuri.org/")
        String wcadenaoriginal);

}
