
package com.gs.ce.ws.core.services.client.validasession;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Valida_sesion", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/C:/ServiciosLogin5/wsdl/portal.socio.gs/Login5/valida_sesion/valida_sesion.asmx.wsdl")
public class ValidaSesion
    extends Service
{

    private final static URL VALIDASESION_WSDL_LOCATION;
    private final static WebServiceException VALIDASESION_EXCEPTION;
    private final static QName VALIDASESION_QNAME = new QName("http://tempuri.org/", "Valida_sesion");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/ServiciosLogin5/wsdl/portal.socio.gs/Login5/valida_sesion/valida_sesion.asmx.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDASESION_WSDL_LOCATION = url;
        VALIDASESION_EXCEPTION = e;
    }

    public ValidaSesion() {
        super(__getWsdlLocation(), VALIDASESION_QNAME);
    }

    public ValidaSesion(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDASESION_QNAME, features);
    }

    public ValidaSesion(URL wsdlLocation) {
        super(wsdlLocation, VALIDASESION_QNAME);
    }

    public ValidaSesion(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDASESION_QNAME, features);
    }

    public ValidaSesion(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidaSesion(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValidaSesionSoap
     */
    @WebEndpoint(name = "Valida_sesionSoap")
    public ValidaSesionSoap getValidaSesionSoap() {
        return super.getPort(new QName("http://tempuri.org/", "Valida_sesionSoap"), ValidaSesionSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidaSesionSoap
     */
    @WebEndpoint(name = "Valida_sesionSoap")
    public ValidaSesionSoap getValidaSesionSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "Valida_sesionSoap"), ValidaSesionSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDASESION_EXCEPTION!= null) {
            throw VALIDASESION_EXCEPTION;
        }
        return VALIDASESION_WSDL_LOCATION;
    }

}
