
package com.gs.ce.ws.core.services.client.datosauxlogin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsDatosAuxiliaresSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsDatosAuxiliaresSoap {


    /**
     * Devuelve los datos de un Empleado Según su Llave Maestra
     * 
     * @param llavMaest
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DatosAuxiliares", action = "http://tempuri.org/DatosAuxiliares")
    @WebResult(name = "DatosAuxiliaresResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DatosAuxiliares", targetNamespace = "http://tempuri.org/", className = "com.gs.ce.ws.core.services.client.datosauxlogin.DatosAuxiliares")
    @ResponseWrapper(localName = "DatosAuxiliaresResponse", targetNamespace = "http://tempuri.org/", className = "com.gs.ce.ws.core.services.client.datosauxlogin.DatosAuxiliaresResponse")
    public String datosAuxiliares(
        @WebParam(name = "LlavMaest", targetNamespace = "http://tempuri.org/")
        String llavMaest);

    /**
     * Devuelve los registros equivalentes al inico Según la cadena enviada, 1=solo nombre y llave maestra, 2= mayor número de campos
     * 
     * @param xtipo
     * @param nombres
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DatosAuxiliaresNombres", action = "http://tempuri.org/DatosAuxiliaresNombres")
    @WebResult(name = "DatosAuxiliaresNombresResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DatosAuxiliaresNombres", targetNamespace = "http://tempuri.org/", className = "com.gs.ce.ws.core.services.client.datosauxlogin.DatosAuxiliaresNombres")
    @ResponseWrapper(localName = "DatosAuxiliaresNombresResponse", targetNamespace = "http://tempuri.org/", className = "com.gs.ce.ws.core.services.client.datosauxlogin.DatosAuxiliaresNombresResponse")
    public String datosAuxiliaresNombres(
        @WebParam(name = "Nombres", targetNamespace = "http://tempuri.org/")
        String nombres,
        @WebParam(name = "xtipo", targetNamespace = "http://tempuri.org/")
        String xtipo);

}
